# GitHub Copilot Configuration
# This file configures GitHub Copilot settings for the repository

# Allowed domains for Copilot to access
# These domains are trusted sources that Copilot can fetch information from
allowed_domains:
  # Standard license providers
  - "www.gnu.org"          # GNU licenses (GPL, LGPL, AGPL)
  - "opensource.org"       # Open Source Initiative
  - "choosealicense.com"   # GitHub's license chooser
  - "spdx.org"            # Software Package Data Exchange
  - "creativecommons.org" # Creative Commons licenses
  - "apache.org"          # Apache Software Foundation
  - "fsf.org"             # Free Software Foundation

  # Documentation and standards
  - "semver.org"          # Semantic Versioning
  - "keepachangelog.com"  # Changelog standards
  - "conventionalcommits.org" # Commit message standards

  # GitHub and related
  - "github.com"          # GitHub main site
  - "docs.github.com"     # GitHub documentation
  - "raw.githubusercontent.com" # GitHub raw content

  # Package managers and registries
  - "npmjs.com"           # npm registry
  - "pypi.org"            # Python Package Index
  - "packagist.org"       # PHP Composer packages
  - "rubygems.org"        # Ruby gems

  # Standards and specifications
  - "json-schema.org"     # JSON Schema
  - "w3.org"              # W3C standards
  - "ietf.org"            # IETF RFCs and standards

  # PHP and Joomla specific
  - "joomla.org"          # Joomla CMS
  - "docs.joomla.org"     # Joomla documentation
  - "php.net"             # PHP documentation

  # Dolibarr specific
  - "dolibarr.org"        # Dolibarr ERP/CRM
  - "wiki.dolibarr.org"   # Dolibarr wiki

# Settings for code generation and suggestions
copilot:
  # Enable Copilot for this repository
  enabled: true

  # File patterns to include for Copilot suggestions
  include:
    - "**/*.py"
    - "**/*.js"
    - "**/*.php"
    - "**/*.md"
    - "**/*.yml"
    - "**/*.yaml"
    - "**/*.json"
    - "**/*.xml"
    - "**/*.sh"

  # File patterns to exclude from Copilot suggestions
  exclude:
    - "**/node_modules/**"
    - "**/vendor/**"
    - "**/build/**"
    - "**/dist/**"
    - "**/.git/**"
    - "**/LICENSE"
    - "**/CHANGELOG.md"

# Notes:
# ------
# - This configuration allows GitHub Copilot to fetch information from trusted sources
# - License providers are included to help with license text and compliance information
# - Package registries help with dependency management and version checking
# - Standards organizations provide authoritative specifications
# - Platform-specific sites (Joomla, Dolibarr, PHP) support our technology stack
# - All domains listed are well-known, reputable sources in their respective domains
# - This list focuses on read-only access to public information
# - No authentication credentials should be used with these domains
